config/routes.rb
GestionMagasin::Application.routes.draw do
  devise_for :users

  resources :produits
  match "csv" => "produits#csv_import"
  root :to => "produits#index"
  match "liste_produits" => "produits#liste_produits"

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    user ||= User.new # guest user
    
    if user.role? :root
      can :manage, :all
    else
      can :read, :all
      if user.role?(:user)
        can :create, Produit
        can :update, Produit
      end
    end
  end
end

app/models/produit.rb
class Produit < ActiveRecord::Base
  has_many :factures , :through => :ventes
  has_many :ventes
  validates_presence_of :nom
  scope :tout,:order => "created_at DESC"
  require 'csv'
  # def self.tout(page)
  #   @posts = Produit.paginate :page =>page, :per_page => 7, :order => 'created_at DESC'
  # end
  def self.search(search)
    tout.where('nom LIKE ?', "%#{search}%")
  end
  def self.create_by_csv(file)
    n=0
    CSV.foreach(file, :col_sep =>';') do |row|
      c=Produit.new
      n=n+1
      c.ref=row[1]
      c.nom=row[5]
      c.prix=row[8]
      c.save
    end
    return n
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  ROLE = [:root,:admin,:user,:guest]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  validates_uniqueness_of :login
  validates_presence_of :login, :password
  validates_confirmation_of :password
  attr_accessible :login, :role, :password, :password_confirmation, :remember_me
  def role?(r)
  	r == ROLE[role-1]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] ="Access denied."
    redirect_to new_user_session_path
  end  
end

app/controllers/produits_controller.rb
class ProduitsController < ApplicationController
  load_and_authorize_resource
  before_filter :find_produit, :only => [:show, :edit, :update, :destroy]
  # GET /produits
  # GET /produits.xml
  def index
    @produits =  Produit.search(params[:search]).paginate :page => params[:page],:per_page => 7
    @produit = Produit.new
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => Produit.all }
    end
  end

  # GET /produits/1
  # GET /produits/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @produit }
    end
  end

  # GET /produits/new
  # GET /produits/new.xml
  def new
    @produit = Produit.new

   # respond_to do |format|
  #    format.html # new.html.erb
  #    format.xml  { render :xml => @produit }
  #  end
  end
  def liste_produits
   @title="Liste Des Produits"
   @produits = Produit.tout
   prawnto :prawn => {
      :page_size => 'A4',
      :left_margin => 50,
      :right_margin => 50,
      :top_margin => 24,
      :bottom_margin => 24}, 
      :filename=>"#{@title.gsub(' ','_')}.pdf" 
   render :layout=>false
  end

  # GET /produits/1/edit
  def edit
  end

  # POST /produits
  # POST /produits.xml
  def create
    @produit = Produit.new(params[:produit])
      if @produit.save
        @produits = Produit.tout.paginate :page => params[:page],:per_page => 7 
        flash[:notice] = 'Produit was successfully created.'
      end
  end

  # PUT /produits/1
  # PUT /produits/1.xml
  def update
    @produit.update_attributes(params[:produit])
    @produits = Produit.tout.paginate :page => params[:page],:per_page => 7 
  end

  # DELETE /produits/1
  # DELETE /produits/1.xml
  def destroy
    @produit.destroy
    flash[:notice] = "Prouduit efface."
  end

  def csv_import
    n= Produit.create_by_csv params[:dump][:file]
    flash.now[:message]="CSV Import Successfuly ,#{n} new records added to data base"
    @produit = Produit.new
    @produits = Produit.tout.paginate :page => params[:page],:per_page => 7 
    render :action => "index"
  end
  protected    
    def find_produit
      @produit = Produit.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/produits_helper.rb
module ProduitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :all %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>

    <div id="container">
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= link_to current_user.login, edit_user_registration_path %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div>

 <div id="flash">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>

      </div>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>

    </div>
  </body>
</html>

app/views/produits/_form.html.erb
<%= form_for(@produit,:remote => true) do |f| %>
 <div id= "erreur_produit" style="display:none"></div>
   <div class="field">
    <%= f.label "Reference :" %>
    <%= f.text_field :ref %>
  </div>
  <div class="field">
    <%= f.label "Description :" %>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label "Prix :" %>
    <%= f.text_field :prix %>
  </div>
  <div class="actions">
  <% if @produit.id %>
    <%= f.submit "Mise a jour" %>
  <% else %>
    <%= f.submit "Nouvaux Produit" %>
  <% end %>
  </div>
<% end %>

app/views/produits/_produit.html.erb
<% if div %>
  <div id="produit_<%= produit.id %>" class="produit">
<% end %>

<div class="edit_tools">
  <div><%= produit.nom %></div>
  <% if can? :update, produit %>
  <%= link_to (image_tag("icon/page_white_edit.png",:alt => "Editer",:title =>"Editer")), edit_produit_path(produit), :remote => true %>
  <% end %>
  <% if can? :delete, produit %>
  <%= link_to (image_tag("icon/page_white_delete.png",:alt => "Effacer",:title =>"Effacer")), produit, :confirm => 'Are you sure?', :method => :delete,:remote => true %>
  <% end %>
</div>
<div class="info_prod" >
  <div>Ref: <%= produit.ref %></div>
  <div>Prix: <%=number_to_currency  produit.prix  %></div>
</div>
<% if div %>
</div>
<% end %>

app/views/produits/_produits.html.erb
<div id="produit_new" class="produit">
    <%= render :partial => "form" %>
</div>
<% produits.each do |produit| %>
    <%= render :partial => "produit",:locals => { :produit => produit, :div  => true} %>
<% end %>
<div class="clear"></div>

app/views/produits/create.js.erb
<% if @produit.errors.any? -%>
  /*Hide the flash notice div*/
  $("flash").hide(300);

  /*Update the html of the div post_errors with the new one*/
  $("erreur_produit").update("<%= escape_javascript(error_messages_for(@produit))%>");

  /*Show the div post_errors*/
  $("erreur_produit").show(300);
<% else -%>
  /*Hide the div post_errors*/
  $("erreur_produit").hide(300);

  /*Update the html of the div flash_notice with the new one*/
  $("flash").update("<div id="flash_notice"><%= escape_javascript(flash[:notice])%></div>");

  /*Show the flash_notice div*/
  $("flash").show(300);

  /*Clear the entire form*/
  /*$(":input:not(input[type=submit])").val("")*/

  /*Replace the html of the div post_lists with the updated new one*/
  $("produit_new").insert(  {after:"<%= escape_javascript( render(:partial => "produit",:locals => { :produit => @produit, :div  => true}))%>"});
<% end -%>

app/views/produits/destroy.js.erb
$("flash").update("<% flash.each do |name, msg| %><%= escape_javascript(content_tag :div, msg, :id => "flash_#{name}") %><% end %>");
  <% flash.clear %>
Effect.BlindUp("produit_<%= @produit.id %>");
$("flash").blinddown(300);

app/views/produits/edit.html.erb
<h1>Editing produit</h1>

<%= render 'form' %>

<%= link_to 'Show', @produit %> |
<%= link_to 'Back', produits_path %>

app/views/produits/edit.js.erb
$("produit_<%= @produit.id %>").childElements()[1].update("<%= escape_javascript(render(:partial => "form"))%>");

app/views/produits/index.html.erb
<% content_for :title do %>
  <%= "List des produits" %>
<% end %>

<h1><%=  yield(:title) %></h1>

<div id="list_produits">
<%= form_tag produits_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Recherche", :name => nil %>
  </p>
<% end %>
<%= will_paginate @produits %>
  <div id="produit_new" class="produit">
    <%= render :partial => "form" %>
  </div>
 <%= render :partial => 'produit', :collection => @produits,:locals => { :div  => true} %>

<br />

<%= link_to 'Nouvaux produit', new_produit_path %>
 <%= form_for :dump, :url=>'/csv', :html => { :multipart => true } do |f| -%>
 <table">
   <tr>
     <td>
      <label for="dump_file">
        Select a CSV File :
      </label>
     </td>
     <td >
       <%= f.file_field :file -%>
     </td>
   </tr>
   <tr>
     <td colspan='2'>
       <%= submit_tag 'Submit' -%>
     </td>
   </tr>
 </table>
<% end -%>

app/views/produits/new.html.erb
<h1>New produit</h1>

<%= render 'form' %>

<%= link_to 'Back', produits_path %>

app/views/produits/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Ref:</b>
  <%= @produit.ref %>
</p>
<p>
  <b>Nom:</b>
  <%= @produit.nom %>
</p>

<p>
  <b>Prix:</b>
  <%= @produit.prix %>
</p>

<p>
  <% if can? :update, @produit %>
    <%= link_to 'Edit', edit_produit_path(@produit) %> |
  <% end %>
  <% if can? :destroy, @produit %>
    <%= link_to "Destroy", @produit, :method => :delete, :confirm => "Are you sure?" %> |
  <% end %>
  <%= link_to 'Back', produits_path %>
</p>

app/views/produits/update.js.erb
<% if @produit.errors.any? -%>
  $("flash").hide(300);
  $("erreur_produit").update("<%= escape_javascript(error_messages_for(@produit))%>");
  $("erreur_produit").show(300);
<% else -%>
  $("erreur_produit").hide(300);
  $("erreur_produit").update("<%= escape_javascript(flash[:notice])%>");
  $("erreur_produit").show(300);
  $("produit_<%= @produit.id %>").update("<%= escape_javascript( render(:partial => "produit",:locals => { :produit => @produit, :div  => false}) ) %>");
<% end -%>